web command - collect all roles for an AWS Fed App (idp) at once
okta/okta-aws-cli pull request #146
Opened 2023-10-10 23:32 UTC by monde

### Collect all AWS IdPs/Roles at once

Based on @daniel-sampliner`s work in #94

`okta-aws-cli` will collect all available AWS IAM Roles for a given IdP at once.
This is a feature specific to writing the `$HOME/.aws/credentials` file. Roles
will be AWS account alias name (if STS list aliases is available on the given
role) then `-` then abbreviated role name.

```
# AWS account alias "myorg", given IdP associated with "AWS Account Federation"
# and an app associated with two roles.

$ okta-aws-cli web \
    --org-domain test.okta.com \
    --oidc-client-id 0oa5wyqjk6Wm148fE1d7 \
    --write-aws-credentials \
    --all-profiles

? Choose an IdP: AWS Account Federation
Updated profile "myorg-S3-read" in credentials file "/Users/me/.aws/credentials".
Updated profile "myorg-S3-write" in credentials file "/Users/me/.aws/credentials".
```

2023-10-10 23:36 UTC, duytiennguyen-okta approved these changes

2023-10-10 23:44 UTC, duytiennguyen-okta requested changes
Everything looks fine. I just have concerned with the way you use the Credential interface

2023-10-10 23:53 UTC, duytiennguyen-okta commented on internal/output/aws_credentials_file.go
> +	cfc := oc.(*oaws.CredsFileCredential)
I really don't like that we have to cast things into concrete type from an interface{}. That has already introduce a lot of issue in the tf provider. Even in the v3 of tfsdk framework, they removed that. I would much rather you defined whatever field you need in the interface and exposing them that way

2023-10-11 00:13 UTC, duytiennguyen-okta approved these changes

2023-10-11 00:22 UTC, merged

2023-10-12 17:36 UTC, monde commented
This was released in v2.0.0-beta.3 but the feature is not complete. The feature is being refined in v2.0.0-beta.4

2023-10-12 17:40 UTC, monde commented
```
go run cmd/okta-aws-cli/main.go web --oidc-client-id abc --org-domain test.oktapreview.com --open-browser --all-profiles --write-aws-credentials

https://test.oktapreview.com/activate?user_code=QLBKHCCB

Updated profile "devorg-idp1-role1" in credentials file "/Users/me/.aws/credentials".
Updated profile "devorg-idp1-role2" in credentials file "/Users/me/.aws/credentials".
Updated profile "devorg-idp2-role1" in credentials file "/Users/me/.aws/credentials".
Updated profile "prodorg-idp1-role1" in credentials file "/Users/me/.aws/credentials".
```